### ISSUE TITLE
Doesn't work if the production/staging site is password protected

### ISSUE THREAD

**Issue by elliottmangham** [pdclark/uploads-by-proxy#13]
Hello,

I have added this to my local on different projects before it works fine if I am grabbing images from live sites, but if I am trying to get images from a production/staging server from my local computer, it doesn't work.

I believe this is because the production/staging server is username and password protected.

Is there a way to overcome these credentials (I have the logins) so I can call those images?

Kind regards

**Comment by Dreamsorcerer** [comment]
I added a fix for this a while back. The author merged it in last year, and it should be in the new version of the plugin that appears to have been released 2 days ago. You'll need to include the login details in the URL e.g. http://user:password@example.com/

**Comment by elliottmangham** [comment]
Thanks @Dreamsorcerer
