### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by Dreamsorcerer** [pdclark/uploads-by-proxy#4]
The extension doesn't seem to be working. Is it still compatible with the current release of WordPress?

I've defined 'UBP_SITEURL', 'UBP_LIVE_DOMAIN' and 'UBP_IS_LOCAL', but not getting anything to work.

**Comment by Dreamsorcerer** [comment]
Fixed the issues that stopped it working, and added support for basic auth, will look at proposing a merge tomorrow.

**Comment by Dreamsorcerer** [comment]
All the issues I found with the plugin have been fixed with pull requests #6 #7 #8 and #9.

**Comment by Dreamsorcerer** [comment]
The fixes have been merged. Now we just need a new release on wordpress.org with the fixes.

**Comment by MunkyMead** [comment]
Has this been released?

**Comment by Dreamsorcerer** [comment]
No, "Last Updated: 10 months ago".
https://en-gb.wordpress.org/plugins/uploads-by-proxy/

**Comment by devonmather** [comment]
@Dreamsorcerer To confirm, is this plugin still working for you currently? I've pulled the latest source down from your pull requests. It's not appearing to have any effect on my development site though :/
